name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote add space https://imDrizzle:$HF_TOKEN@huggingface.co/spaces/imDrizzle/lurien-matrix
          git fetch space main || true
          git merge space/main --allow-unrelated-histories -m "Merge HF models" || true
          git push space main
